### PR TITLE
add customizable OpenAI API model parameter

### PR DESCRIPTION
**Pull request by lfsevergnini**
### What's new

This PR adds a new parameter to the `freeedcom/ai-codereviewer` Github Action: `OPENAI_API_MODEL`, which enables its users to customize the OpenAI model as needed.

### Why

As mentioned in issue #12, a possible reason for a "404 Not Found" error while posting a request to OpenAI API's endpoint is that [the API Key doesn't have access to the `gpt-4` model](https://github.com/freeedcom/ai-codereviewer/issues/12#issuecomment-1625873825).

With these updates, it'll be possible to use another OpenAI model e.g. `gpt-3.5-turbo` instead.

### CODE REVIEW

**Comment by lfsevergnini** [comment]
@villesau I didn't find any guidelines on how to contribute, so I inspected the latest commits in the main branch.

I ran `yarn package` after saving my changes. FYI used Node 18.

Please let me know if you want me to follow a different approach.

**Comment by sadath-12** [comment]
@lfsevergnini would try out your version as well

**Review by bbernstein — APPROVED** [review]
Very helpful addition, works well for me.

**Comment by villesau** [comment]
Nice, looks great! And sorry for being slow with merging this. I'll release the new version to marketplace shortly.

**Pull request merged**
